<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2000/REC-xhtml1-20000126/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title><?php echo $lang['msg']['err']; ?></title>
	<style type="text/css">

	</style>
</head>
<body>

	<div id="all"><p><strong><?php echo $lang['msg']['err']; ?>!</strong><br /> <?php echo $this->message; ?></p></div>
	
</body>
</html>
